apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xkcd-explorer.gradioDemoName" . }}
  labels:
    {{- include "xkcd-explorer.labels" . | nindent 4 }}
    {{- include "xkcd-explorer.gradioDemoSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "xkcd-explorer.gradioDemoSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xkcd-explorer.gradioDemoSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xkcd-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "gradio-demo"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.demo.image.registry}}/{{ .Values.demo.image.repository }}:{{ .Values.demo.image.tag }}"
          imagePullPolicy: {{ .Values.demo.image.pullPolicy }}
          env:
            - name: GRADIO_SERVER_PORT
              value: "80"
            - name: SERVER_URL
              value: "http://{{ include "xkcd-explorer.fullname" . }}:{{ .Values.server.service.port }}"
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
