apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xkcd-explorer.torchserveName" . }}
  labels:
    {{- include "xkcd-explorer.labels" . | nindent 4 }}
    {{- include "xkcd-explorer.torchserveSelectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "xkcd-explorer.torchserveSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xkcd-explorer.torchserveSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xkcd-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "torchserve-server"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.torchserve.image.registry}}/{{ .Values.torchserve.image.repository }}:{{ .Values.torchserve.image.tag }}"
          imagePullPolicy: {{ .Values.torchserve.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 7070
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
