FROM python:3.9

COPY client client

# Install poetry
RUN pip install poetry

WORKDIR /demo

# Cache dependency install
COPY demo/pyproject.toml demo/poetry.lock .
RUN poetry install --no-root --no-dev

COPY demo .
RUN poetry install --no-dev

ENTRYPOINT ["poetry", "run", "xkcd-explorer-demo"]
CMD ["gradio"]
