apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "xkcd-explorer.demoDataJobName" . }}
  labels:
    {{- include "xkcd-explorer.labels" . | nindent 4 }}
    {{- include "xkcd-explorer.demoDataJobSelectorLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xkcd-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: "import-data"
        image: "{{ .Values.demo.image.registry}}/{{ .Values.demo.image.repository }}:{{ .Values.demo.image.tag }}"
        imagePullPolicy: {{ .Values.demo.image.pullPolicy }}
        args: ["import-data"]
        env:
          - name: SERVER_URL
            value: "{{ include "xkcd-explorer.fullname" . }}:{{ .Values.server.service.port }}"
      restartPolicy: Never
  backoffLimit: 1
