server:
  image:
    registry: docker.io
    repository: xkcd-explorer/server
    pullPolicy: IfNotPresent
    tag: latest

  replicaCount: 1

  service:
    type: ClusterIP
    port: 50051

torchserve:
  image:
    registry: docker.io
    repository: xkcd-explorer/torchserve
    pullPolicy: IfNotPresent
    tag: latest

  replicaCount: 1

  service:
    type: ClusterIP
    port: 7070

demo:
  image:
    registry: docker.io
    repository: xkcd-explorer/demo
    pullPolicy: IfNotPresent
    tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
